config/routes.rb
Housed::Application.routes.draw do
  resources :shows
  resources :guests

  resources :users do
  end
    
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/welcome', :to => 'pages#welcome'
  
  match '/thanks', :to => 'guests#thanks'
  
  

end

app/models/show.rb
class Show < ActiveRecord::Base
  attr_accessible :date, :host_email, :location, :ticket_price, :tickets_max,
                  :tickets_min
#  belongs_to :host_id, class_name: "User"
  belongs_to :user
  has_many :guests
  
  validates :date, :host_email, :location, :ticket_price, 
            :tickets_max, :tickets_min, presence: true

#  validates :musician_id, presence: true

  
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  # GET /shows
  # GET /shows.json
  
  before_filter :signed_in_user,
                only: [:index, :edit, :update, :destroy, :following, :followers]
  before_filter :correct_user,   only: [ :edit]
  before_filter :admin_user, only: [:index, :destroy]


  def index
    @shows = Show.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shows }
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = Show.find(params[:id])
    @musician = User.find(@show.user_id).name
    @guests = @show.guests.count
    @guest = @show.guests.build(params[:guest])
    flash[:show] = @show
 #   flash.keep    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/new
  # GET /shows/new.json
  def new
    @show = Show.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @show }
    end
  end



  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = current_user.shows.build(params[:show])

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render json: @show, status: :created, location: @show }
      else
        format.html { render action: "new" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shows/1
  # PUT /shows/1.json
  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update_attributes(params[:show])
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url }
      format.json { head :no_content }
    end
  end
  private

    def correct_user
      @show = current_user.shows.find_by_id(params[:id])
      redirect_to root_path if @show.nil?
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
    
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_buy_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/_buy_modal.html.erb
<div id="myModal" class="modal hide fade">
            <div class="modal-header">
              <button class="close" data-dismiss="modal">&times;</button>
              <h3>Housed - A new kind of live music</h3>
            </div>
            <div class="modal-body">
              <h4>Buy!</h4>
			  <%= render 'buy_form' %>
              <hr>
            </div>
            <div class="modal-footer">
			  <%= link_to "Buy!", root_path, confirm: 'Are you sure?', class: "btn btn-primary btn-large", method: :buy %>
            </div>
          </div>
          <a data-toggle="modal" href="#myModal" class="btn btn-primary btn-large">Buy a ticket &raquo;</a>

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :host_email %><br />
    <%= f.text_field :host_email %>
  </div>
  <div class="field">
    <%= f.label :ticket_price %><br />
    <%= f.number_field :ticket_price %>
  </div>
  <div class="field">
    <%= f.label :tickets_min %><br />
    <%= f.number_field :tickets_min %>
  </div>
  <div class="field">
    <%= f.label :tickets_max %><br />
    <%= f.number_field :tickets_max %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/buy.html.erb
<h1>Buy!</h1>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<h1>Listing shows</h1>

<%= render 'shared/shows' %>

<br />

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New show</h1><br><br>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<h1>
  <%= @musician %>
</h1>House Show<br><br>


<p>
  <b>Date:</b>
  <%= @show.date %>
</p>

<p>
  <b>Location:</b>
  <%= @show.location %>
</p>

<p>
  <b>Host:</b>
  <%= @show.host_email %>
</p>

<p>
  <b>Ticket price:</b>
  $<%= @show.ticket_price %>
</p>

<% if @guests > 4 %>

	<p>
	  <b>Guests:</b>
	  <%= @guests %>
	</p>
<% end %>

<% if signed_in? %>
<p>
  <b>Tickets min:</b>
  <%= @show.tickets_min %>
</p>

<p>
  <b>Tickets max:</b>
  <%= @show.tickets_max %>
</p>


	<%= link_to 'Edit', edit_show_path(@show) %> |
	<%= link_to 'Back', shows_path %>

<% else %>
	<%= render 'buy_modal' %>
<% end %>