config/routes.rb
Housed::Application.routes.draw do
  resources :shows
  resources :guests

  resources :users do
  end
    
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/welcome', :to => 'pages#welcome'
  
  match '/thanks', :to => 'guests#thanks'
  
  

end

app/views/layouts/_footer.html.erb
<footer>
	<hr>
	<p>&copy; Housed 2012</p>

	<nav>
	   <ul>
	     <li><%= link_to "About",   about_path %></li>
	     <li><%= link_to "Contact", contact_path %></li>
	   </ul>
	 </nav>

</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Housed</a>
      <div class="nav-collapse">



        <ul class="nav">

			<li><%= link_to "Home", root_path %></li>
			
		</ul>
          <% if signed_in? %>
			<ul class="nav">
            <% if current_user.musician? %>
				<li><%= link_to "Create show", new_show_path %></li>
				<li><%= link_to "Manage shows", current_user %></li>

			<% end%>
			<li><%= link_to "Help", help_path %></li>
			</ul>			
			<ul class="nav pull-right">			
	            <li id="fat-menu" class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                Account <b class="caret"></b>
	              </a>
	              <ul class="dropdown-menu">
	                <li><%= link_to "Profile", current_user %></li>
	                <li><%= link_to "Settings", edit_user_path(current_user) %></li>

	                <li class="divider"></li>
	                <li>
	                  <%= link_to "Sign out", signout_path, method: "delete" %>
	                </li>
	              </ul>
	            </li>
			
          <% else %>
			<ul class="nav pull-right">				
            	<li><%= link_to "Sign in", signin_path %></li>
			</ul>
          <% end %>
			</ul>
		

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>

	<%= yield %>

  <%= render 'layouts/footer' %>

  <%= javascript_include_tag "application" %>

</body>
</html>